# Custom Language File for Launcher Customizer

[ejs.app]
title = "ModdedZoo Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/xqWgTkmw8s"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "Bienvenue à ModdedZoo"
welcomeDescription = "Notre mission reproduire le meilleur parc animalier de Minecraft pour sensibiliser la population sur les animaux."
welcomeDescCTA = "Vous êtes juste à quelques clic de ModdedZoo."
